# Generated by Django 4.2.27 on 2025-12-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('booked', 'Reservado'), ('in_progress', 'En curso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='booked', max_length=12, verbose_name='Estado'),
        ),
    ]
